# Generated by Django 4.0.5 on 2022-09-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='book_img/')),
            ],
            options={
                'verbose_name': 'Фотография для книги',
                'verbose_name_plural': 'Фотографии для книг',
            },
        ),
        migrations.CreateModel(
            name='BookImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ManyToManyField(to='Books.img')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
    ]
