# Generated by Django 4.0.5 on 2022-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_img_bookimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ManyToManyField(to='Books.img'),
        ),
        migrations.DeleteModel(
            name='BookImg',
        ),
    ]
