# Generated by Django 4.0.5 on 2022-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_img_delete_bookimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
