# Generated by Django 4.0.5 on 2022-09-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_genre_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorIMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='author_img/')),
            ],
            options={
                'verbose_name': 'Фотография для автора',
                'verbose_name_plural': 'Фотографии для авторов',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ManyToManyField(to='Books.authorimg'),
        ),
    ]
