# Generated by Django 4.0.5 on 2022-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_authorimg_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ManyToManyField(null=True, to='Books.authorimg'),
        ),
    ]
