# Generated by Django 4.0.5 on 2022-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_author_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreIMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='genre_img')),
            ],
            options={
                'verbose_name': 'Фотография для жанра',
                'verbose_name_plural': 'Фотографии для жанров',
            },
        ),
        migrations.AddField(
            model_name='genre',
            name='img',
            field=models.ManyToManyField(to='Books.genreimg'),
        ),
    ]
