# Generated by Django 4.0.5 on 2022-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_alter_author_img_alter_author_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=32),
        ),
    ]
